# Compiled artifact — generated by Agent 2 from TC_AMAZON_GUEST_001 agentic execution
# Source of truth: specs/TC_AMAZON_GUEST_001.md
# Execution that produced this file: EXEC_20260928_004 (status=PASSED)
import time

import pytest
import allure

from pages.amazon_home_page import AmazonHomePage
from pages.amazon_search_results_page import AmazonSearchResultsPage
from pages.amazon_product_page import AmazonProductPage

SEARCH_TERM = "iPhone 18 Pro Max"


@pytest.mark.spec_id("TC_AMAZON_GUEST_001")
def test_guest_search_and_view_product(page, exec_context, step_logger):
    home = AmazonHomePage(page)
    results = AmazonSearchResultsPage(page)
    product = AmazonProductPage(page)

    # STEP_001 — Navigate to the Amazon homepage.
    with step_logger.allure_step("STEP_001", "Navigate to the Amazon homepage"):
        t0 = time.time()
        home.navigate()
        step_logger.record(
            "STEP_001",
            "Navigate to the Amazon homepage.",
            "Amazon homepage should be displayed with the search bar visible.",
            "PASSED",
            actual_result="Amazon homepage displayed; search bar visible",
            locator="locator('#twotabsearchtextbox')",
            duration_ms=int((time.time() - t0) * 1000),
        )

    # STEP_002 — Enter search term.
    with step_logger.allure_step("STEP_002", f"Enter '{SEARCH_TERM}' into the search bar"):
        t0 = time.time()
        home.enter_search_term(SEARCH_TERM)
        step_logger.record(
            "STEP_002",
            f'Enter "{SEARCH_TERM}" into the search bar.',
            "The search term should be accepted and visible in the search bar.",
            "PASSED",
            actual_result=f"Search bar contains: {SEARCH_TERM!r}",
            locator="locator('#twotabsearchtextbox')",
            duration_ms=int((time.time() - t0) * 1000),
        )

    # STEP_003 — Submit the search.
    with step_logger.allure_step("STEP_003", "Submit the search"):
        t0 = time.time()
        home.submit_search()
        results.wait_for_results()
        n = results.results_count()
        step_logger.record(
            "STEP_003",
            "Submit the search.",
            f'Search results page should be displayed with listings related to "{SEARCH_TERM}".',
            "PASSED",
            actual_result=f"Search results page displayed ({n} product cards)",
            locator="get_by_role('button', name='Go')",
            duration_ms=int((time.time() - t0) * 1000),
        )

    # STEP_004 — Open first matching product.
    with step_logger.allure_step("STEP_004", "Open the first matching product"):
        t0 = time.time()
        results.open_first_result()
        product.wait_for_page()
        assert "/dp/" in page.url, f"Expected product page URL to contain /dp/, got: {page.url}"
        step_logger.record(
            "STEP_004",
            "Open the first matching product from the search results.",
            "The product detail page should be displayed.",
            "PASSED",
            actual_result="Product detail page displayed; URL contains /dp/",
            locator="locator(\"[data-component-type='s-search-result'] .a-size-medium.a-color-base.a-text-normal\").first",
            duration_ms=int((time.time() - t0) * 1000),
        )

    # STEP_005 — Verify product title.
    with step_logger.allure_step("STEP_005", "Verify product title relevance"):
        t0 = time.time()
        title = product.get_title()
        product.verify_title_relevance(SEARCH_TERM.split())
        step_logger.record(
            "STEP_005",
            "Verify the product title on the product detail page.",
            f'The product title should be relevant to "{SEARCH_TERM}".',
            "PASSED",
            actual_result=f"Product title: {title!r}",
            locator="locator('#productTitle')",
            duration_ms=int((time.time() - t0) * 1000),
        )

    exec_context.write_execution_json("PASSED", step_logger.results())
