# Compiled artifact — generated by Agent 2 (Execution Agent)
from __future__ import annotations
from playwright.sync_api import Page, expect
from pages.base_page import BasePage


class AmazonPLPPage(BasePage):
    def __init__(self, page: Page) -> None:
        super().__init__(page)
        self.result_cards   = page.locator("[data-component-type='s-search-result']")
        self.first_result   = page.locator(".a-link-normal.s-no-outline")
        self.sort_dropdown  = page.locator("#s-result-sort-select")
        self.filter_section = page.locator("#s-refinements")

    def wait_for_results(self) -> None:
        self.result_cards.first.wait_for(state="visible", timeout=30_000)

    def get_result_count(self) -> int:
        return self.result_cards.count()

    def open_first_result(self) -> None:
        self.first_result.first.click()

    def sort_by(self, option_value: str) -> None:
        self.sort_dropdown.select_option(label=option_value)
        self.result_cards.first.wait_for(state="visible", timeout=15_000)

    def verify_results_visible(self) -> None:
        expect(self.result_cards.first).to_be_visible()
