# Compiled artifact — generated by Agent 2 (Execution Agent)
from __future__ import annotations
from playwright.sync_api import Page, expect
from pages.base_page import BasePage


class AmazonCheckoutPage(BasePage):
    def __init__(self, page: Page) -> None:
        super().__init__(page)
        self.email_input    = page.locator("#ap_email")
        self.continue_btn   = page.locator("input[name='continue']")
        self.order_summary  = page.locator(".a-box-inner")

    def wait_for_page(self) -> None:
        self.page.wait_for_timeout(2000)

    def proceed_as_guest(self, email: str = "") -> None:
        if self.email_input.count() > 0 and self.email_input.is_visible():
            if email:
                self.email_input.fill(email)
            self.continue_btn.click()
            self.page.wait_for_timeout(2000)

    def verify_order_summary(self) -> None:
        self.page.wait_for_timeout(1000)
        content = self.page.content().lower()
        assert any(w in content for w in ("order", "summary", "total", "checkout")),             "Order summary not found on page"

    def verify_payment_step(self) -> None:
        self.page.wait_for_timeout(1000)
        content = self.page.content().lower()
        assert any(w in content for w in ("payment", "credit card", "pay", "billing")),             "Payment step not found on page"
