# Compiled artifact — generated by Agent 2 (Execution Agent)
from __future__ import annotations
from playwright.sync_api import Page, expect
from pages.base_page import BasePage

URL = "https://www.amazon.com"


class AmazonHomePage(BasePage):
    def __init__(self, page: Page) -> None:
        super().__init__(page)
        self.search_bar    = page.locator("#twotabsearchtextbox")
        self.search_submit = page.locator("#nav-search-submit-button")
        self.nav_bar       = page.locator("#navbar")

    def navigate(self) -> None:
        self.goto(URL)
        expect(self.search_bar).to_be_visible()

    def enter_search_term(self, term: str) -> None:
        self.search_bar.fill(term)
        expect(self.search_bar).to_have_value(term)

    def submit_search(self) -> None:
        self.search_submit.click()

    def verify_loaded(self) -> None:
        expect(self.search_bar).to_be_visible()
        expect(self.nav_bar).to_be_visible()
