# Compiled artifact — generated by Agent 2 from TC_AMAZON_GUEST_001 agentic execution
# Locators discovered from live DOM on 2026-09-28 (EXEC_20260928_004)
from __future__ import annotations

from playwright.sync_api import Page, expect

from pages.base_page import BasePage


class AmazonProductPage(BasePage):
    def __init__(self, page: Page) -> None:
        super().__init__(page)
        # Confirmed present: #productTitle on dp/ page for iPhone 17 Pro Max result
        self.product_title = page.locator("#productTitle")

    def wait_for_page(self) -> None:
        expect(self.product_title).to_be_visible()

    def get_title(self) -> str:
        return self.product_title.inner_text().strip()

    def verify_title_relevance(self, keywords: list[str]) -> None:
        title = self.get_title().lower()
        assert any(kw.lower() in title for kw in keywords), (
            f"Product title {title!r} does not contain any of {keywords}"
        )
