# Compiled artifact — generated by Agent 2 (Execution Agent)
from __future__ import annotations
from playwright.sync_api import Page, expect
from pages.base_page import BasePage


class AmazonPDPPage(BasePage):
    def __init__(self, page: Page) -> None:
        super().__init__(page)
        self.product_title  = page.locator("#productTitle")
        self.price          = page.locator(".a-price .a-offscreen").first
        self.add_to_cart    = page.locator("#add-to-cart-button")
        self.availability   = page.locator("#availability")
        self.product_images = page.locator("#imgTagWrapperId img")

    def wait_for_page(self) -> None:
        self.product_title.wait_for(state="visible", timeout=30_000)

    def get_title(self) -> str:
        return self.product_title.inner_text().strip()

    def verify_title_contains(self, keyword: str) -> None:
        title = self.get_title().lower()
        assert keyword.lower() in title, f"Expected {keyword!r} in title {title!r}"

    def verify_price_visible(self) -> None:
        expect(self.price).to_be_visible()

    def verify_purchase_controls(self) -> None:
        expect(self.add_to_cart).to_be_visible()

    def click_add_to_cart(self) -> None:
        self.add_to_cart.click()
        self.page.wait_for_timeout(2000)
