# Compiled artifact — generated by Agent 2 (Execution Agent)
from __future__ import annotations
from playwright.sync_api import Page, expect
from pages.base_page import BasePage

CART_URL = "https://www.amazon.com/gp/cart/view.html"


class AmazonCartPage(BasePage):
    def __init__(self, page: Page) -> None:
        super().__init__(page)
        self.cart_items       = page.locator(".a-spacing-mini")
        self.quantity_select  = page.locator(".a-dropdown-container select")
        self.delete_button    = page.locator("input[value='Delete']")
        self.subtotal         = page.locator("#sc-subtotal-amount-activecart")
        self.proceed_checkout = page.locator("#sc-buy-box-ptc-button")

    def navigate(self) -> None:
        self.goto(CART_URL)
        self.page.wait_for_timeout(2000)

    def get_item_count(self) -> int:
        return self.cart_items.count()

    def verify_item_in_cart(self, keyword: str) -> None:
        content = self.page.content().lower()
        assert keyword.lower() in content, f"Expected {keyword!r} in cart"

    def verify_item_not_in_cart(self, keyword: str) -> None:
        content = self.page.content().lower()
        assert keyword.lower() not in content, f"Did not expect {keyword!r} in cart"

    def remove_first_item(self) -> None:
        self.delete_button.first.click()
        self.page.wait_for_timeout(2000)

    def update_quantity(self, item_index: int, quantity: int) -> None:
        selects = self.quantity_select.all()
        if item_index < len(selects):
            selects[item_index].select_option(str(quantity))
            self.page.wait_for_timeout(2000)

    def proceed_to_checkout(self) -> None:
        self.proceed_checkout.click()
        self.page.wait_for_timeout(2000)
