# Compiled artifact — generated by Agent 2 from TC_AMAZON_GUEST_001 agentic execution
# Locators discovered from live DOM on 2026-09-28 (EXEC_20260928_004)
from __future__ import annotations

from playwright.sync_api import Page, expect

from pages.base_page import BasePage

URL = "https://www.amazon.com"


class AmazonHomePage(BasePage):
    def __init__(self, page: Page) -> None:
        super().__init__(page)
        # Locator: semantic ID confirmed present on live DOM
        self.search_bar = page.locator("#twotabsearchtextbox")
        # Locator: ID selector is more precise; get_by_role("button", name="Go")
        # matched 2 elements in pytest mode (hamburger menu also resolved).
        self.search_submit = page.locator("#nav-search-submit-button")

    def navigate(self) -> None:
        self.goto(URL)
        expect(self.search_bar).to_be_visible()

    def enter_search_term(self, term: str) -> None:
        self.search_bar.fill(term)
        expect(self.search_bar).to_have_value(term)

    def submit_search(self) -> None:
        self.search_submit.click()
